name: Format, Lint And Test Code

on: # [push, pull_request]
  push:
    branches:
      main
  # pull_request:

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Super Linter
        uses: github/super-linter@v4.8.5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.8

      - name: Install and Configure Odoo
        uses: ./.github/workflows/install-configure-odoo.yml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          pytest ./account_account_balance/tests/test*