name: Install and Configure Odoo 14

on: [push]

jobs:
  install-odoo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: check git available on system
        run: which git

      - name: Update Server
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Postgresql
        run: |
          sudo apt-get install postgresql -y

      - name: Install Python pip Dependencies
        run: | 
          sudo apt-get install libpq-dev python-dev libxml2-dev libxslt1-dev libldap2-dev libsasl2-dev libffi-dev
          sudo -H pip3 install -r https://raw.githubusercontent.com/odoo/odoo/14.0/requirements.txt

      - name: Install Other Required Packages
        run: |
          sudo apt-get install nodejs npm -y
          sudo npm install -g rtlcss
          
      - name: Install WKHTMLTOPDF
        run: |
          sudo apt-get install xfonts-75dpi
          sudo apt-get install xfonts-base
          sudo wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
          sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb
          sudo cp /usr/local/bin/wkhtmltoimage /usr/bin/wkhtmltoimage
          sudo cp /usr/local/bin/wkhtmltopdf /usr/bin/wkhtmltopdf

      - name: Create Log Directory
        run: |
          sudo mkdir /var/log/odoo
          sudo touch /var/log/odoo/odoo.log

      - name: Upload Log File
        uses: actions/upload-artifact@v2
        with:
          name: odoo-log-file
          path: /var/log/odoo/odoo.log

      - name: Install Odoo
        run: |
          mkdir odoo14
          cd odoo14
          git clone -b 14.0 https://github.com/odoo/odoo.git
          pip3 install -r odoo/requirements.txt
          
      - name: Create Server Config
        run: |
          sudo cp ./odoo.conf /etc/.

      - name: Start Odoo
        run: |
          cd odoo14/odoo
          pip3 install PyPDF2
          sudo ./odoo-bin -c /etc/odoo.conf &
          ifconfig

      - name: Check if odoo runs locally
        run: |
          curl localhost:8069 >> output.txt

#      - name: Read wget file
#        run: cat index.html

#      - name: Print Working Directory
#        run: |
#          pwd
#          tail -f /var/log/odoo/odoo.log

  download-odoo-log-file:
    runs-on: ubuntu-latest
    steps:
      - name: Download odoo-log Artifact
        uses: actions/download-artifact@v2
        with:
          name: odoo-log-file

      - name: Tail log file
        run: |
          tail -f odoo-log-file
    needs: install-odoo
