name: Install and Configure Odoo 14

on: [push]

jobs:
  install-odoo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: check git available on system
        run: which git

      - name: Update Server
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

#      - name: Create Odoo User in Ubuntu
#        run: |
#          sudo adduser -system -home=/opt/odoo -group odoo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Postgresql
        run: |
          sudo apt-get install postgresql -y

      - name: Create Odoo User for Postgresql
        run: |
          sudo su – postgres -c “createuser -s odoo” 2> /dev/null || true

#      - name: Install Python Dependencies
#        run: |
#          sudo apt-get install git python3 python3-pip build-essential wget python3-dev python3-venv python3-wheel libxslt-dev libzip-dev libldap2-dev libsasl2-dev python3-setuptools node-less libjpeg-dev gdebi -y

      - name: Install Python pip Dependencies
        run: | 
          sudo apt-get install libpq-dev python-dev libxml2-dev libxslt1-dev libldap2-dev libsasl2-dev libffi-dev
          sudo -H pip3 install -r https://raw.githubusercontent.com/odoo/odoo/master/requirements.txt

      - name: Install Other Required Packages
        run: |
          sudo apt-get install nodejs npm -y
          sudo npm install -g rtlcss
          
      - name: Install WKHTMLTOPDF
        run: |
          sudo apt-get install xfonts-75dpi
          sudo wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
          sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb
          sudo cp /usr/local/bin/wkhtmltoimage /usr/bin/wkhtmltoimage
          sudo cp /usr/local/bin/wkhtmltopdf /usr/bin/wkhtmltopdf

      - name: Create Log Directory
        run: |
          sudo mkdir /var/log/odoo
          sudo chown odoo:odoo /var/log/odoo

      - name: Install Odoo
        run: |
          sudo apt-get install git
          sudo git clone –depth 1 –branch 14.0 https://www.github.com/odoo/odoo /odoo/odoo-server

#      - name: Setting Permissions on Home Folder
#        run: |
#          sudo chown -R odoo:odoo /odoo/*
          
      - name: Create Server Config
        run: |
          sudo touch /etc/odoo-server.conf
          sudo su root -c “printf ‘[options] \n; This is the password that allows database operations:\n’ >> /etc/odoo-server.conf”
          sudo su root -c “printf ‘admin_passwd = admin\n’ >> /etc/odoo-server.conf”
          sudo su root -c “printf ‘xmlrpc_port = 8069\n’ >> /etc/odoo-server.conf”
          sudo su root -c “printf ‘logfile = /var/log/odoo/odoo-server.log\n’ >> /etc/odoo-server.conf”
          sudo su root -c “printf ‘addons_path=/odoo/odoo-server/addons\n’ >> /etc/odoo-server.conf”
          sudo chown odoo:odoo /etc/odoo-server.conf
          sudo chmod 640 /etc/odoo-server.conf

      - name: Start Odoo
        run: |
          cd /odoo/odoo-server
          ./odoo-bin -c /etc/odoo-server.conf

      - name: Print Working Directory
        run: |
          pwd
