name: Format, Configure Odoo and Test Code

on: # [push, pull_request]
  push:
    branches:
      main
  # pull_request:

jobs:
  format-code:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Super Linter
        uses: github/super-linter@v4.8.5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  install-configure-odoo:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Server
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup Postgresql v12
        uses: ireznik/postgis-action@v12
        with:
          postgresql version: '12-master'  # See https://hub.docker.com/r/postgis/postgis for available versions, if it is not specified, use the default value 'latest'
          postgresql password: 'odoo'   # This environment variable sets the superuser password for PostgreSQL, maybe string or secrets, the default superuser is defined by the input environment variable: postgresql user.
          postgresql user: 'odoo'  # This optional environment variable is used in conjunction with postgresql password to set a user and its password. This variable will create the specified user with superuser power and a database with the same name. If it is not specified, then the default user of 'postgres' will be used.
          postgresql db: 'odoo_test'  # This optional environment variable can be used to define a different name for the default database that is created when the image is first started. If it is not specified, then the value of postgresql user will be used.

      - name: Install Python pip Dependencies
        run: |
          sudo apt-get install libpq-dev python-dev libxml2-dev libxslt1-dev libldap2-dev libsasl2-dev libffi-dev
          sudo -H pip3 install -r https://raw.githubusercontent.com/odoo/odoo/14.0/requirements.txt

      - name: Install Other Required Packages
        run: |
          sudo apt-get install nodejs npm -y
          sudo npm install -g rtlcss

      - name: Install WKHTMLTOPDF
        run: |
          sudo apt-get install xfonts-75dpi
          sudo apt-get install xfonts-base
          sudo wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
          sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb
          sudo cp /usr/local/bin/wkhtmltoimage /usr/bin/wkhtmltoimage
          sudo cp /usr/local/bin/wkhtmltopdf /usr/bin/wkhtmltopdf

      - name: Create Log Directory
        run: |
          sudo mkdir /var/log/odoo
          sudo touch /var/log/odoo/odoo.log

      - name: Install Odoo
        run: |
          mkdir odoo14
          cd odoo14
          git clone -b 14.0 https://github.com/odoo/odoo.git
          pip3 install -r odoo/requirements.txt

      - name: Create Server Config
        run: |
          sudo cp ./odoo.conf /etc/.

      - name: Start Odoo
        run: |
          cd odoo14/odoo
          pip3 install PyPDF2
          sudo ./odoo-bin -d odoo_test -i base -c /etc/odoo.conf &
          ifconfig

      - name: Check if odoo runs locally
        run: |
          wget localhost:8069
      #          curl localhost:8069 >> output.txt

      - name: Read Output file
        run: cat index.html

      - name: Upload Log File
        uses: actions/upload-artifact@v2
        with:
          name: odoo-log-file
          path: /var/log/odoo/odoo.log
    needs: format-code

  download-odoo-log-file:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download odoo-log Artifact
        uses: actions/download-artifact@v2
        with:
          name: odoo-log-file

      - name: Read log file
        run: |
          cat odoo.log
    needs: install-configure-odoo

  test-code:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install Pytest
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          pytest ./account_account_balance/tests/test*
    needs: download-odoo-log-file