name: Odoo Service

on: push

jobs:
  odoo-docker:
    runs-on: self-hosted

    services:
      odoo:
        image: odoo:14.0
        ports:
          - 8069:8069

      postgres-db:
        image: postgres
        env:
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: postgres
          POSTGRES_USER: odoo

    steps:
      - name: Assign Folder To User1
        run: |
          sudo chown -R user1:user1 /home/user1/actions-runner/_work

      - name: Checkout
        uses: actions/checkout@v2

      - name: Check if odoo runs locally
        run: |
          wget odoo:8069
          cat index.html